import * as React from 'react';

interface EmailTemplateProps {
    id: string,
    firstName: string,
    lastName: string,
    email: string,
}

export const EmailNewReservationCustomer: React.FC<Readonly<EmailTemplateProps>> = ({id, firstName, lastName, email}) => (
    <div>
        <p>Hi {firstName} {lastName},</p>
        <p></p>
        <p>We just wanted to inform you that we have received your reservation.</p>
        <p>We will contact you for further.</p><br/>
        <p></p>
        <p>This e-mail is autogenerated and you can't respond to it.</p>
        <p>For any question email us to info@casa-fragola.com</p>
        <img src={`${process.env.NEXTAUTH_URL}/logo.png`} alt="Casa Fragola Logo"/>
    </div>
);